//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolHockeyBOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int I_Pk { get; set; }
        public System.DateTime T_LastUpdate { get; set; }
    }
}
