//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolHockeyBOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastPlayerInfo
    {
        public int I_ApiId { get; set; }
        public string C_Team { get; set; }
        public string C_Pos { get; set; }
        public string C_Name { get; set; }
        public int I_Point { get; set; }
        public int I_Pk { get; set; }
        public bool L_Traded { get; set; }
        public System.DateTime D_Date { get; set; }
    }
}
