//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolHockeyBOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayoffUserInfo
    {
        public int I_Pk { get; set; }
        public string C_Code { get; set; }
        public string C_UserEmail { get; set; }
        public string C_DisplayName { get; set; }
        public string C_Pic { get; set; }
        public int I_Games { get; set; }
        public int I_Goals { get; set; }
        public int I_Assists { get; set; }
        public int I_Points { get; set; }
        public int I_BestDay { get; set; }
        public System.DateTime D_BestDay { get; set; }
        public int I_BestMonth { get; set; }
        public System.DateTime D_BestMonth { get; set; }
        public int I_BestLastD { get; set; }
        public int I_PtLastD { get; set; }
        public int I_PtLastW { get; set; }
        public int I_PtLastM { get; set; }
    }
}
