//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoolHockeyBOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSchedule
    {
        public int I_TeamSchedulePk { get; set; }
        public string C_Team { get; set; }
        public System.DateTime D_Date { get; set; }
    }
}
